steps:
# Build the container images
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/content-web', '--target', 'web', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/content-assistant', '--target', 'assistant', '.']

# Push the container images to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/content-web']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/content-assistant']

# Deploy web service to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'content-web'
  - '--image'
  - 'gcr.io/$PROJECT_ID/content-web'
  - '--region'
  - 'asia-east1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '5001'
  - '--memory'
  - '512Mi'
  - '--set-env-vars'
  - 'FLASK_APP=app.py,FLASK_ENV=production'
  - '--set-secrets'
  - 'OPENAI_API_KEY=openai-api-key:latest,TWITTER_API_KEY=twitter-api-key:latest,TWITTER_API_SECRET=twitter-api-secret:latest,TWITTER_ACCESS_TOKEN=twitter-access-token:latest,TWITTER_ACCESS_TOKEN_SECRET=twitter-access-token-secret:latest,TWITTER_BEARER_TOKEN=twitter-bearer-token:latest,SMTP_PASSWORD=smtp-password:latest'

# Deploy assistant service to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'content-assistant'
  - '--image'
  - 'gcr.io/$PROJECT_ID/content-assistant'
  - '--region'
  - 'asia-east1'
  - '--platform'
  - 'managed'
  - '--no-allow-unauthenticated'
  - '--memory'
  - '512Mi'
  - '--set-env-vars'
  - 'TZ=Asia/Shanghai'
  - '--set-secrets'
  - 'OPENAI_API_KEY=openai-api-key:latest,TWITTER_API_KEY=twitter-api-key:latest,TWITTER_API_SECRET=twitter-api-secret:latest,TWITTER_ACCESS_TOKEN=twitter-access-token:latest,TWITTER_ACCESS_TOKEN_SECRET=twitter-access-token-secret:latest,TWITTER_BEARER_TOKEN=twitter-bearer-token:latest,SMTP_PASSWORD=smtp-password:latest'

images:
- 'gcr.io/$PROJECT_ID/content-web'
- 'gcr.io/$PROJECT_ID/content-assistant'

timeout: '1800s'
